root /usr/share/nginx/html;
include /etc/nginx/mime.types;

resolver 127.0.0.11 valid=10s ipv6=off;
set $api http://api:8000;

client_max_body_size 8m;

location /api/analysis {
    rewrite ^/api/(.*)$ /$1 break;
    include /etc/nginx/snippets/proxy-api.conf;
    proxy_read_timeout 180s;
}

location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    include /etc/nginx/snippets/proxy-api.conf;
}

location / {
    try_files $uri $uri/ /index.html;
}
