#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the AstroJobs monorepo.
# Installs system + project dependencies, initialises a local Postgres
# cluster with pgvector, and writes a development .env. Safe to re-run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

export PATH="$HOME/.local/bin:$PATH"

PGDATA="$HOME/.local/share/astrojobs/pgdata"
PG_PORT="5432"
PG_SUPERUSER="postgres"
DB_USER="astrojobs"
DB_PASSWORD="astrojobs"
DB_NAME="astrojobs"

log() { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }

pg_bin() {
  ls -d /usr/lib/postgresql/*/bin 2>/dev/null | sort -V | tail -1
}

install_postgres() {
  local pgbin
  pgbin="$(pg_bin)"
  if [ -n "$pgbin" ] && [ -f "$("$pgbin/pg_config" --sharedir)/extension/vector.control" ]; then
    log "PostgreSQL + pgvector already installed"
    return
  fi
  log "Installing PostgreSQL 17 + pgvector"
  . /etc/os-release
  sudo install -d /usr/share/postgresql-common/pgdg
  sudo curl -sS -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc \
    https://www.postgresql.org/media/keys/ACCC4CF8.asc
  echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" \
    | sudo tee /etc/apt/sources.list.d/pgdg.list >/dev/null
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    postgresql-17 postgresql-17-pgvector
}

install_uv() {
  if command -v uv >/dev/null 2>&1; then
    log "uv already installed ($(uv --version))"
    return
  fi
  log "Installing uv"
  curl -LsSf https://astral.sh/uv/install.sh | sh
}

install_moto() {
  if command -v moto_server >/dev/null 2>&1; then
    log "moto_server already installed"
    return
  fi
  log "Installing moto_server (local S3 mock)"
  uv tool install "moto[server]"
}

init_cluster() {
  local pgbin
  pgbin="$(pg_bin)"
  if [ ! -f "$PGDATA/PG_VERSION" ]; then
    log "Initialising Postgres cluster at $PGDATA"
    mkdir -p "$PGDATA"
    "$pgbin/initdb" -D "$PGDATA" -U "$PG_SUPERUSER" --auth=trust --encoding=UTF8 >/dev/null
    {
      echo "port = $PG_PORT"
      echo "listen_addresses = 'localhost'"
      echo "unix_socket_directories = '/tmp'"
    } >> "$PGDATA/postgresql.conf"
  else
    log "Postgres cluster already initialised"
  fi
}

start_pg_temporarily() {
  local pgbin
  pgbin="$(pg_bin)"
  if "$pgbin/pg_ctl" -D "$PGDATA" status >/dev/null 2>&1; then
    return
  fi
  "$pgbin/pg_ctl" -D "$PGDATA" -o "-p $PG_PORT" -w -l "$PGDATA/postgresql.log" start >/dev/null
}

provision_db() {
  local pgbin
  pgbin="$(pg_bin)"
  start_pg_temporarily
  log "Provisioning role + database"
  "$pgbin/psql" -h /tmp -p "$PG_PORT" -U "$PG_SUPERUSER" -d postgres -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD' SUPERUSER;
  END IF;
END
\$\$;
SQL
  if ! "$pgbin/psql" -h /tmp -p "$PG_PORT" -U "$PG_SUPERUSER" -d postgres -tAc \
      "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1; then
    "$pgbin/psql" -h /tmp -p "$PG_PORT" -U "$PG_SUPERUSER" -d postgres \
      -c "CREATE DATABASE $DB_NAME OWNER $DB_USER"
  fi
}

write_env() {
  if [ -f "$REPO_ROOT/.env" ]; then
    log ".env already exists, leaving it untouched"
    return
  fi
  log "Writing development .env"
  cat > "$REPO_ROOT/.env" <<ENV
# Local development configuration (generated by .cursor/install.sh)
POSTGRES_HOST=localhost
POSTGRES_PORT=$PG_PORT
POSTGRES_USER=$DB_USER
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=$DB_NAME

ENVIRONMENT=development
COOKIE_SECURE=false
JWT_SECRET=dev-secret-change-me
FRONTEND_ORIGIN=http://localhost:3000

EMBEDDING_PROVIDER=local
EMBEDDING_DIMENSIONS=1024

AWS_REGION=us-east-1
AWS_S3_BUCKET=astrojobs-resumes
AWS_S3_ENDPOINT_URL=http://localhost:4566
AWS_ACCESS_KEY_ID=test
AWS_SECRET_ACCESS_KEY=test

VITE_API_URL=/api
ENV
}

install_node_deps() {
  log "Installing pnpm workspace dependencies"
  corepack enable >/dev/null 2>&1 || true
  pnpm install --frozen-lockfile
}

install_python_deps() {
  log "Syncing API Python dependencies (uv)"
  (cd "$REPO_ROOT/apps/api" && uv sync)
}

install_postgres
install_uv
install_moto
init_cluster
provision_db
write_env
install_node_deps
install_python_deps

log "install.sh finished"
