"""add resume ownership to documents

Revision ID: 3f41dae8ebfe
Revises: 1df3ffccb20f
Create Date: 2026-08-21 12:52:20.568468

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f41dae8ebfe'
down_revision: str | Sequence[str] | None = '1df3ffccb20f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_key', sa.String(length=1024), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_documents_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_documents_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_column('storage_key')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
