"""add resume_analyses table

Revision ID: 85f0ccefb40a
Revises: 3f41dae8ebfe
Create Date: 2026-08-21 17:29:18.409530

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '85f0ccefb40a'
down_revision: str | Sequence[str] | None = '3f41dae8ebfe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_document_id', sa.Integer(), nullable=False),
    sa.Column('job_source', sa.String(length=20), nullable=False),
    sa.Column('job_document_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resume_analyses_user_id_users')),
    sa.ForeignKeyConstraint(['resume_document_id'], ['documents.id'], name=op.f('fk_resume_analyses_resume_document_id_documents')),
    sa.ForeignKeyConstraint(['job_document_id'], ['documents.id'], name=op.f('fk_resume_analyses_job_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_analyses'))
    )
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_analyses_resume_document_id'), ['resume_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_resume_document_id'))

    op.drop_table('resume_analyses')
    # ### end Alembic commands ###
