"""Canonical technology names accepted by recruiter job postings."""

TECHNOLOGIES: tuple[str, ...] = (
    ".NET",
    "Android",
    "Angular",
    "Ansible",
    "Apache Airflow",
    "Apache Kafka",
    "AWS",
    "Azure",
    "C",
    "C#",
    "C++",
    "Cassandra",
    "ClickHouse",
    "Cloudflare",
    "CSS",
    "Cypress",
    "Dart",
    "Databricks",
    "Django",
    "Docker",
    "Elasticsearch",
    "Elixir",
    "FastAPI",
    "Figma",
    "Firebase",
    "Flask",
    "Flutter",
    "GCP",
    "Git",
    "GitHub Actions",
    "GitLab CI",
    "Go",
    "Grafana",
    "GraphQL",
    "HTML",
    "iOS",
    "Java",
    "JavaScript",
    "Jenkins",
    "Jest",
    "Kotlin",
    "Kubernetes",
    "Laravel",
    "Linux",
    "Looker",
    "MariaDB",
    "MongoDB",
    "MySQL",
    "NestJS",
    "Next.js",
    "Node.js",
    "NoSQL",
    "NumPy",
    "OpenAI API",
    "Oracle",
    "Pandas",
    "PHP",
    "Pinecone",
    "Playwright",
    "PostgreSQL",
    "Power BI",
    "Prometheus",
    "PyTorch",
    "Python",
    "RabbitMQ",
    "React",
    "React Native",
    "Redis",
    "Ruby",
    "Ruby on Rails",
    "Rust",
    "Salesforce",
    "Scala",
    "Selenium",
    "Snowflake",
    "Spark",
    "Spring Boot",
    "SQL",
    "SQLite",
    "Svelte",
    "Swift",
    "Tableau",
    "Tailwind CSS",
    "TensorFlow",
    "Terraform",
    "TypeScript",
    "Vue.js",
)

_ALIASES = {
    "amazon web services": "AWS",
    "dotnet": ".NET",
    "golang": "Go",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "js": "JavaScript",
    "k8s": "Kubernetes",
    "node": "Node.js",
    "nodejs": "Node.js",
    "postgres": "PostgreSQL",
    "reactjs": "React",
    "ts": "TypeScript",
    "vue": "Vue.js",
}

_BY_KEY = {technology.casefold(): technology for technology in TECHNOLOGIES}


def canonical_technology(value: str) -> str | None:
    key = value.strip().casefold()
    if not key:
        return None
    return _ALIASES.get(key) or _BY_KEY.get(key)
