name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start API and database
        run: docker compose up -d --build db api

      - name: Run API tests
        run: docker compose exec -T api uv run pytest

      - name: Stop containers
        if: always()
        run: docker compose down

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/astrojobs

            git pull origin main

            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"

            docker compose down
            docker compose up -d --build
